### ISSUE TITLE
Faraday 1.0.0 compatibility

### ISSUE THREAD

**Issue by nowakov** [avadev/AvaTax-REST-V2-Ruby-SDK#71]
Hey guys!

Faraday 1.0.0 was released recently and avatax gem does not support it. It's causing conflicts with other gems that depend on faraday too. Do you have any plans to bump faraday version?

**Comment by nowakov** [comment]
@contygm any news on that?

**Comment by pdamer** [comment]
This would be really helpful. I'm running into conflicts also.

**Comment by pdamer** [comment]
its fixed in this PR: https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/pull/74

**Comment by nowakov** [comment]
@shilpa-khanal Can we get that merged and released?

**Comment by shilpa-khanal** [comment]
Please check https://rubygems.org/gems/avatax/versions/20.6.0 for the latest release. Cheers!

**Comment by nowakov** [comment]
@shilpa-khanal Version 20.6.0 is still not compatible with faraday 1.0

```
Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    avatax (= 20.6.0) was resolved to 20.6.0, which depends on
      faraday_middleware-parse_oj (~> 0.3.2) was resolved to 0.3.2, which depends on
        faraday (~> 0.9)

    sentry-raven (= 3.0.0) was resolved to 3.0.0, which depends on
      faraday (>= 1.0)


```

**Comment by jwenger100** [comment]
This issue is already fixed last comment is asking to release from master which we are doing regularly
